apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    name: http
  clusterIP: None
  selector:
    name: elasticsearch-data
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
  labels:
    app: elasticsearch-cluster
spec:
  ports:
  - port: 9300
    name: cluster-comms
  clusterIP: None
  selector:
    app: elasticsearch
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: elasticsearch-master
spec:
  serviceName: "elasticsearch-master"
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
        name: elasticsearch-master
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: elasticsearch
        image: quay.io/samsung_cnct/elasticsearch:0.1
        ports:
        - containerPort: 9300
        resources:
          limits:
            cpu: 200m
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 4Gi
        env:
        - name: CLUSTER_NAME
          value: "k8s-production"
        - name: NODE_DATA
          value: "false"
        - name: NODE_MASTER
          value: "true"
        - name: SERVICE
          value: "elasticsearch-cluster"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g -Djava.net.preferIPv4Stack=true"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        imagePullPolicy: Always
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: esdata
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: elasticsearch-data
spec:
  serviceName: "elasticsearch-data"
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
        name: elasticsearch-data
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: elasticsearch
        image: quay.io/samsung_cnct/elasticsearch:0.1
        ports:
        - containerPort: 9300
        - containerPort: 9200
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 4Gi
        env:
        - name: CLUSTER_NAME
          value: "k8s-production"
        - name: NODE_DATA
          value: "true"
        - name: NODE_MASTER
          value: "false"
        - name: SERVICE
          value: "elasticsearch-cluster"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g -Djava.net.preferIPv4Stack=true"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        imagePullPolicy: Always
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: esdata
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi